export const route = {
  home: "/",
  login: "/login",
  users: "/users",
  items: "/items",
  itemDetail: "/user/item",
  saved: "/saved",
  messages: "/messages",
  myItem: "/my_item",
  myItemEdit: "/my_item/edit",
  shopPage: "/shop_page",
  transactionChat: "/transaction/chat",
  favorite: "/favorite",
  approvals: "/approvals",
  profile: "/",
  launch: "/launch",
  archiveDetail: "/archive-detail",
};
