services:
  flask:
    environment:
      - FLASK_ENV=production
    env_file:
      - ./backend/.env.production

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        MODE: production
    command: ["/bin/sh", "-c", "npm run build"]
    volumes:
      - ./frontend/app/dist:/dist

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl
      - ./frontend/app/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80" # http://<EC2のIP>:8080 でアクセス
    environment:
      PMA_HOST: ourvintagedb.cneu42i26p7f.ap-northeast-1.rds.amazonaws.com
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: ourVintageAdmin
    depends_on:
      - flask
    networks:
      - app_network
