version: "3.8"

services:
  flask:
    container_name: flask_app
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    ports:
      - "5001:5001"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
