export const brandList = [
  { key: 1, name: "Adidas アディダス" },
  { key: 2, name: "Arrow アロー" },
  { key: 3, name: "Alden オールデン" },
  { key: 4, name: "Brooks Brothers ブルックスブラザーズ" },
  { key: 5, name: "Barbour バブアー" },
  { key: 6, name: "Bad Otis" },
  { key: 7, name: "Birkenstock ビルケン" },
  { key: 8, name: "BIG MAC" },
  { key: 9, name: "Belstaff" },
  { key: 10, name: "BigBen" },
  { key: 11, name: "Bates ベイツ" },
  { key: 12, name: "Big smith" },
  { key: 13, name: "BIG YANK" },
  { key: 14, name: "BEN DAVIS ベンデイビス" },
  { key: 15, name: "BIG MIKE" },
  { key: 16, name: "Buco" },
  { key: 17, name: "BRENT" },
  { key: 18, name: "Champion チャンピオン" },
  { key: 19, name: "Carhartt カーハート" },
  { key: 20, name: "CONVERSE" },
  { key: 21, name: "Columbia コロンビア" },
  { key: 22, name: "CHIPPEWA チペワ" },
  { key: 23, name: "COOGI クージー" },
  { key: 24, name: "Dickies" },
  { key: 25, name: "DEE CEE" },
  { key: 26, name: "Eddie Bauer" },
  { key: 27, name: "ELY" },
  { key: 28, name: "Eastwest" },
  { key: 29, name: "Fireking" },
  { key: 30, name: "Five Brother" },
  { key: 31, name: "FILSON" },
  { key: 32, name: "FRUIT OF THE LOOM" },
  { key: 33, name: "GRAMICCI" },
  { key: 34, name: "GUNNE SAX" },
  { key: 35, name: "GLOVERALL" },
  { key: 36, name: "Harley-Davidson" },
  { key: 37, name: "Hanes" },
  { key: 38, name: "Harris Tweed" },
  { key: 39, name: "Healthknit" },
  { key: 40, name: "J.Crew" },
  { key: 41, name: "J.C.Penney" },
  { key: 42, name: "Jantzen" },
  { key: 43, name: "Jimmy’s" },
  { key: 44, name: "King Louie" },
  { key: 45, name: "Levi’s" },
  { key: 46, name: "LACOSTE" },
  { key: 47, name: "L.L.Bean" },
  { key: 48, name: "Lee" },
  { key: 49, name: "McGREGOR" },
  { key: 50, name: "Maverick" },
  { key: 51, name: "NIKE" },
  { key: 52, name: "NEW BALANCE" },
  { key: 53, name: "North Beach Leather" },
  { key: 54, name: "Osh kosh オシュコシュ" },
  { key: 55, name: "PENDLETON ペンドルトン" },
  { key: 56, name: "Patagonia" },
  { key: 57, name: "Penney’s" },
  { key: 58, name: "PUMA" },
  { key: 59, name: "Powderhorn" },
  { key: 60, name: "POWELL PERALTA パウエルペラルタ" },
  { key: 61, name: "Ralph Lauren ラルフローレン" },
  { key: 62, name: "RED WING" },
  { key: 63, name: "Russell" },
  { key: 64, name: "Red kap" },
  { key: 65, name: "RockyMountain Featherbed" },
  { key: 66, name: "SANTA CRUZ" },
  { key: 67, name: "Sears" },
  { key: 68, name: "STUSSY ストューシー" },
  { key: 69, name: "SCHOTT ショット" },
  { key: 70, name: "SEBAGO セバゴ" },
  { key: 71, name: "Sanders" },
  { key: 72, name: "SKOOKUM スクーカム" },
  { key: 73, name: "THE NORTH FACE ノースフェイス" },
  { key: 74, name: "TOMMY HILFIGER" },
  { key: 75, name: "Timberland" },
  { key: 76, name: "TOWN CRAFT" },
  { key: 77, name: "THRASHER" },
  { key: 78, name: "VANS" },
  { key: 79, name: "VANSON" },
  { key: 80, name: "Wrangler ラングラー" },
  { key: 81, name: "WOOLRICH ウールリッチ" },
  { key: 82, name: "WHITE’S ホワイツ" },
  { key: 83, name: "WESCO ウェスコ" },
];
