export const genres = [
  { brandKey: "0", brandName: "90's" },
  { brandKey: "1", brandName: "80's" },
  { brandKey: "2", brandName: "70's" },
  { brandKey: "3", brandName: "60's" },
  { brandKey: "4", brandName: "50's" },
  { brandKey: "5", brandName: "Porter Yoshida & Co." },
  { brandKey: "6", brandName: "The Real McCoys" },
  { brandKey: "7", brandName: "Sacai" },
  { brandKey: "8", brandName: "Sasquatchfabrix" },
  { brandKey: "9", brandName: "Snow Peak" },
  { brandKey: "10", brandName: "Beams" },
  { brandKey: "11", brandName: "Issey Miyake" },
  { brandKey: "12", brandName: "Visvim" },
  { brandKey: "13", brandName: "Noir Kei Ninomiya" },
  { brandKey: "14", brandName: "Auralee" },
  { brandKey: "15", brandName: "EDWIN" },
  { brandKey: "16", brandName: "and Wander" },
  { brandKey: "17", brandName: "WTAPS" },
  { brandKey: "18", brandName: "Undercover" },
  { brandKey: "19", brandName: "Facetasm" },
];
