export const genres = [
  { brandKey: 0, brandName: "90's" },
  { brandKey: 1, brandName: "80's" },
  { brandKey: 2, brandName: "70's" },
  { brandKey: 3, brandName: "60's" },
  { brandKey: 4, brandName: "50's" },
  { brandKey: 5, brandName: "MILITARY ミリタリー" },
  { brandKey: 6, brandName: "WORK ワーク" },
  { brandKey: 7, brandName: "OUTDOOR アウトドア" },
  { brandKey: 8, brandName: "SKATE スケート" },
  { brandKey: 9, brandName: "DENIM デニム" },
  { brandKey: 10, brandName: "LEATHER レザー" },
  { brandKey: 11, brandName: "GOOD REGULAR グッドレギュラー" },
  { brandKey: 12, brandName: "JUNK ジャンク" },
  { brandKey: 13, brandName: "BAND T-SHIRTS バンT" },
];
